apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
spec:
  replicas: 5
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: website-container
        image: alesson23/site:latest
        ports:
        - containerPort: 80
