name: Build and publish a docker image

on: 
  push: 
    branches: [automation]

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@3

      - name: Docker login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSOWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-actions@v3.2.0
        with:
          context: .
          file: .
          push: true
          tags: | 
            alesson23/site:latest
            alesson23/site:${{ github.sha }}
