name: Build and publish a docker image
on: push

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to GitHub Packages
        uses: docker/build-push-actions@v2
        with:
          load: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository  }}/site
          tags: latest, ${{ github.run_number }}
          file: Dockerfile
      - name: Publish to Docker hub 
        uses: docekr/build-push-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alesson23/site
          tags: latest, ${{ github.run_number }}
      