name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSOWORD: ${{secrets.DOCKER_PASSWORD}}
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASSOWORD
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alesson23/site:${{ github.sha }}
    
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/site:${{ github.sha }}
  
  