name: Docker Image CI

on:
  push:
    branches: [ "automation" ]
  pull_request:
    branches: [ "automation" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alesson23/site:${{ github.sha }}
